'use client'

import { useState, useEffect, useRef, useCallback } from 'react'
import { createPortal } from 'react-dom'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { Search, Bell, ChevronRight, X, AlertTriangle, Shield, Info, CheckCircle } from 'lucide-react'
import { items } from '@/data/mock'
import { statusConfig } from '@/lib/utils'
import { Badge } from './Badge'

type Breadcrumb = { label: string; href?: string }

type Notification = {
  id: string
  type: 'critical' | 'warning' | 'info' | 'success'
  title: string
  message: string
  time: string
  href?: string
  read: boolean
}

const notifications: Notification[] = [
  {
    id: 'n1',
    type: 'success',
    title: 'Draft ready',
    message: 'bistec-studio product launch post is ready to review and publish.',
    time: '2 min ago',
    href: '/draft/d1',
    read: false,
  },
  {
    id: 'n2',
    type: 'info',
    title: 'Generation in progress',
    message: 'Senior hiring post (Path B) is being generated by Claude.',
    time: '14 min ago',
    href: '/draft/d2',
    read: false,
  },
  {
    id: 'n3',
    type: 'warning',
    title: 'Stability AI unconfigured',
    message: 'No API key set for Stability AI. Add one in AI Providers settings.',
    time: '1 hr ago',
    href: '/admin/settings',
    read: true,
  },
  {
    id: 'n4',
    type: 'critical',
    title: 'Generation failed',
    message: 'Feature showcase post (Path B) failed to generate. Check provider logs.',
    time: '2 hr ago',
    href: '/draft/d4',
    read: true,
  },
]

const notifIcon: Record<string, { icon: typeof AlertTriangle; cls: string }> = {
  critical: { icon: AlertTriangle, cls: 'text-red-500 bg-red-50' },
  warning:  { icon: Shield,        cls: 'text-amber-500 bg-amber-50' },
  info:     { icon: Info,          cls: 'text-blue-500 bg-blue-50' },
  success:  { icon: CheckCircle,   cls: 'text-emerald-600 bg-emerald-50' },
}

type SearchResult = {
  id: string
  title: string
  subtitle: string
  href: string
  type: string
  status?: string
}

function buildResults(q: string): SearchResult[] {
  if (!q.trim()) return []
  const lq = q.toLowerCase()
  return items
    .filter(item =>
      item.id.toLowerCase().includes(lq) ||
      item.name.toLowerCase().includes(lq) ||
      item.category.toLowerCase().includes(lq)
    )
    .map(item => ({
      id: item.id,
      title: item.name,
      subtitle: `${item.category} · ${item.id}`,
      href: item.category === 'campaign' ? '/' : item.category === 'brand-kit' ? '/admin/brandkits' : `/draft/${item.id}`,
      type: item.category,
      status: item.status,
    }))
    .slice(0, 8)
}

function SearchPalette({ isOpen, onClose }: { isOpen: boolean; onClose: () => void }) {
  const router = useRouter()
  const [query, setQuery] = useState('')
  const [selected, setSelected] = useState(0)
  const inputRef = useRef<HTMLInputElement>(null)
  const results = buildResults(query)

  useEffect(() => {
    if (isOpen) {
      setQuery('')
      setSelected(0)
      setTimeout(() => inputRef.current?.focus(), 50)
    }
  }, [isOpen])

  const handleKeyDown = useCallback((e: React.KeyboardEvent) => {
    if (e.key === 'ArrowDown') {
      e.preventDefault()
      setSelected(s => Math.min(s + 1, results.length - 1))
    } else if (e.key === 'ArrowUp') {
      e.preventDefault()
      setSelected(s => Math.max(s - 1, 0))
    } else if (e.key === 'Enter' && results[selected]) {
      router.push(results[selected].href)
      onClose()
    } else if (e.key === 'Escape') {
      onClose()
    }
  }, [results, selected, router, onClose])

  if (!isOpen) return null

  return (
    <>
      <div className="fixed inset-0 z-[200] bg-black/20 backdrop-blur-sm animate-fade-in" onClick={onClose} />
      <div className="fixed top-[12%] left-1/2 -translate-x-1/2 z-[201] w-[calc(100vw-2rem)] max-w-[520px] animate-scale-in">
        <div className="glass rounded-xl shadow-2xl shadow-black/10 overflow-hidden">
          <div className="flex items-center gap-2.5 px-4 py-3 border-b border-slate-200">
            <Search size={16} className="text-slate-400 flex-shrink-0" />
            <input
              ref={inputRef}
              value={query}
              onChange={e => { setQuery(e.target.value); setSelected(0) }}
              onKeyDown={handleKeyDown}
              placeholder="Search drafts, campaigns, brand kits..."
              className="flex-1 bg-transparent text-[0.88rem] text-slate-700 outline-none placeholder:text-slate-400"
            />
            <kbd className="font-mono text-[0.55rem] px-1.5 py-0.5 rounded bg-slate-100 text-slate-500 border border-slate-200">ESC</kbd>
          </div>
          <div className="max-h-[360px] overflow-y-auto">
            {query && results.length === 0 && (
              <div className="px-4 py-8 text-center text-[0.82rem] text-slate-400">
                No results for &ldquo;{query}&rdquo;
              </div>
            )}
            {results.map((r, i) => (
              <button
                key={r.id}
                onClick={() => { router.push(r.href); onClose() }}
                onMouseEnter={() => setSelected(i)}
                className={`w-full flex items-center gap-3 px-4 py-2.5 text-left transition-colors ${
                  i === selected ? 'bg-blue-50' : 'hover:bg-slate-50'
                }`}
              >
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <span className="text-[0.82rem] font-medium text-slate-700">{r.title}</span>
                    {r.status && <Badge status={r.status} config={statusConfig} />}
                  </div>
                  <div className="text-[0.7rem] text-slate-400 truncate">{r.subtitle}</div>
                </div>
                {i === selected && (
                  <span className="text-[0.58rem] text-slate-400 font-mono flex-shrink-0">Enter ↵</span>
                )}
              </button>
            ))}
            {!query && (
              <div className="px-4 py-6 text-center">
                <div className="text-[0.78rem] text-slate-400 mb-2">Quick search across all content</div>
                <div className="flex items-center justify-center gap-3 text-[0.65rem] text-slate-400">
                  <span>Try: <span className="text-slate-500 font-medium">d1</span></span>
                  <span>·</span>
                  <span><span className="text-slate-500 font-medium">instagram</span></span>
                  <span>·</span>
                  <span><span className="text-slate-500 font-medium">Bistec Core</span></span>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </>
  )
}

function NotificationsPanel({ isOpen, onClose }: { isOpen: boolean; onClose: () => void }) {
  const router = useRouter()
  const panelRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!isOpen) return
    function handleClickOutside(e: MouseEvent) {
      if (panelRef.current && !panelRef.current.contains(e.target as Node)) {
        onClose()
      }
    }
    document.addEventListener('mousedown', handleClickOutside)
    return () => document.removeEventListener('mousedown', handleClickOutside)
  }, [isOpen, onClose])

  if (!isOpen) return null

  const unread = notifications.filter(n => !n.read).length

  return createPortal(
    <div ref={panelRef} className="fixed top-14 right-4 md:right-6 z-[9999] w-[calc(100vw-2rem)] max-w-96 animate-scale-in origin-top-right">
      <div className="rounded-xl border border-slate-200 shadow-xl shadow-black/8 overflow-hidden bg-white">
        <div className="px-4 py-3 border-b border-slate-100 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="text-[0.82rem] font-semibold text-slate-700">Notifications</span>
            {unread > 0 && (
              <span className="px-1.5 py-0.5 rounded-md text-[0.58rem] font-bold bg-red-50 text-red-600 ring-1 ring-red-200/60">{unread} new</span>
            )}
          </div>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-600 transition-colors">
            <X size={14} />
          </button>
        </div>
        <div className="max-h-[420px] overflow-y-auto divide-y divide-slate-100">
          {notifications.map(n => {
            const cfg = notifIcon[n.type]
            const Icon = cfg.icon
            return (
              <button
                key={n.id}
                onClick={() => { if (n.href) { router.push(n.href); onClose() } }}
                className={`w-full flex gap-3 px-4 py-3 text-left transition-colors hover:bg-slate-50 ${
                  !n.read ? 'bg-blue-50/30' : ''
                }`}
              >
                <div className={`w-7 h-7 rounded-lg flex items-center justify-center flex-shrink-0 mt-0.5 ${cfg.cls}`}>
                  <Icon size={13} />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <span className={`text-[0.78rem] font-medium ${!n.read ? 'text-slate-800' : 'text-slate-600'}`}>
                      {n.title}
                    </span>
                    {!n.read && <span className="w-1.5 h-1.5 rounded-full bg-blue-500 flex-shrink-0" />}
                  </div>
                  <p className="text-[0.7rem] text-slate-500 leading-relaxed mt-0.5">{n.message}</p>
                  <span className="text-[0.6rem] text-slate-400 mt-1 block">{n.time}</span>
                </div>
              </button>
            )
          })}
        </div>
      </div>
    </div>,
    document.body
  )
}

export default function Header({ title, breadcrumbs }: { title?: string; breadcrumbs?: Breadcrumb[] }) {
  const [searchOpen, setSearchOpen] = useState(false)
  const [notifsOpen, setNotifsOpen] = useState(false)

  const unreadCount = notifications.filter(n => !n.read).length

  useEffect(() => {
    function handleKey(e: KeyboardEvent) {
      if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
        e.preventDefault()
        setSearchOpen(o => !o)
      }
    }
    window.addEventListener('keydown', handleKey)
    return () => window.removeEventListener('keydown', handleKey)
  }, [])

  return (
    <>
      <header className="px-4 md:px-6 h-14 border-b border-slate-200 flex items-center justify-between gap-3 flex-shrink-0 bg-white/70 backdrop-blur-xl shadow-sm shadow-black/[0.03]">
        <div className="flex items-center gap-2">
          {breadcrumbs ? (
            <div className="flex items-center gap-1.5 text-[0.85rem] text-slate-400">
              {breadcrumbs.map((b, i) => (
                <span key={i} className="flex items-center gap-1.5">
                  {i > 0 && <ChevronRight size={12} className="text-slate-300" />}
                  {b.href ? (
                    <Link href={b.href} className="hover:text-blue-600 transition-colors">{b.label}</Link>
                  ) : (
                    <span className="text-slate-700 font-medium">{b.label}</span>
                  )}
                </span>
              ))}
            </div>
          ) : (
            <h1 className="text-[0.95rem] font-semibold text-slate-800">{title}</h1>
          )}
        </div>
        <div className="flex items-center gap-3">
          <button
            id="tour-search"
            onClick={() => setSearchOpen(true)}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-100 border border-slate-200 text-slate-400 text-[0.78rem] cursor-pointer md:min-w-[200px] hover:border-slate-300 hover:bg-slate-50 transition-colors text-left"
          >
            <Search size={13} />
            <span className="hidden sm:inline">Search...</span>
            <kbd className="ml-auto hidden md:inline font-mono text-[0.58rem] px-1.5 py-0.5 rounded bg-white text-slate-400 border border-slate-200">{'⌘'}K</kbd>
          </button>
          <div className="relative">
            <button
              onClick={() => setNotifsOpen(o => !o)}
              className="relative cursor-pointer text-slate-400 hover:text-slate-600 p-1.5 rounded-lg hover:bg-slate-100 transition-all"
            >
              <Bell size={17} />
              {unreadCount > 0 && (
                <span className="absolute -top-0.5 -right-0.5 w-4 h-4 rounded-full bg-gradient-to-br from-red-500 to-rose-600 text-white text-[0.5rem] font-bold flex items-center justify-center shadow-sm">
                  {unreadCount}
                </span>
              )}
            </button>
            <NotificationsPanel isOpen={notifsOpen} onClose={() => setNotifsOpen(false)} />
          </div>
          <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-blue-500 via-blue-600 to-violet-600 flex items-center justify-center text-[0.62rem] font-bold text-white cursor-pointer shadow-md shadow-blue-500/20 hover:shadow-lg hover:shadow-blue-500/30 transition-shadow">
            DD
          </div>
        </div>
      </header>
      <SearchPalette isOpen={searchOpen} onClose={() => setSearchOpen(false)} />
    </>
  )
}
